# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b51e1337981f45bc3630905eb516cc6c242e862f978c50bbefc0d19465a17bf4346adac72fc3ed701c062206ca778c18690889251aabc07c3ccd0a4e20b65f7

test:
  secret_key_base: 1d874275863a0d336a5625956d07d66ab6cd675a8f059f74a1e9a0c9cba92bb49dd6d4eab7ee94d8f06162786cfa4ac780c58834c84eb711fc197299b15091e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
